{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to /Users/nils/nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n",
      "[nltk_data] Downloading package averaged_perceptron_tagger to\n",
      "[nltk_data]     /Users/nils/nltk_data...\n",
      "[nltk_data]   Package averaged_perceptron_tagger is already up-to-\n",
      "[nltk_data]       date!\n",
      "[nltk_data] Downloading package stopwords to /Users/nils/nltk_data...\n",
      "[nltk_data]   Package stopwords is already up-to-date!\n"
     ]
    }
   ],
   "source": [
    "import textstat\n",
    "import nltk\n",
    "from nltk.tokenize import sent_tokenize, word_tokenize\n",
    "from nltk.probability import FreqDist\n",
    "from nltk.corpus import stopwords\n",
    "import language_tool_python\n",
    "import statistics\n",
    "import logging\n",
    "\n",
    "# Setup basic logging (you can configure it as needed)\n",
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')\n",
    "\n",
    "# Download necessary NLTK data\n",
    "nltk.download('punkt')\n",
    "nltk.download('averaged_perceptron_tagger')\n",
    "nltk.download('stopwords')\n",
    "\n",
    "def analyze_essay(essay):\n",
    "    \"\"\"\n",
    "    Analyze various aspects of an essay for linguistic sophistication.\n",
    "\n",
    "    :param essay: A string containing the essay text.\n",
    "    :return: A dictionary with various metrics and an overall quality score.\n",
    "    \"\"\"\n",
    "    \n",
    "    tool = language_tool_python.LanguageToolPublicAPI('en-US')\n",
    "\n",
    "    # Readability and complexity metrics\n",
    "    flesch_reading_ease = textstat.flesch_reading_ease(essay)\n",
    "    smog_index = textstat.smog_index(essay)\n",
    "    flesch_kincaid_grade = textstat.flesch_kincaid_grade(essay)\n",
    "\n",
    "    # Tokenize essay into words and sentences\n",
    "    words = word_tokenize(essay)\n",
    "    sentences = sent_tokenize(essay)\n",
    "    unique_words = len(set(words))\n",
    "\n",
    "    # Lexical diversity\n",
    "    lexical_diversity = len(set(words)) / len(words) if words else 0\n",
    "\n",
    "    # Sentence length variability\n",
    "    sentence_lengths = [len(word_tokenize(sentence)) for sentence in sentences]\n",
    "    sentence_length_variability = statistics.stdev(sentence_lengths) if len(sentence_lengths) > 1 else 0\n",
    "\n",
    "    # Grammatical mistakes\n",
    "    matches = tool.check(essay)\n",
    "    grammar_errors = len(matches) \n",
    "\n",
    "    return   {\n",
    "        \"flesch_reading_ease\": flesch_reading_ease,\n",
    "        \"smog_index\": smog_index,\n",
    "        \"flesch_kincaid_grade\": flesch_kincaid_grade,\n",
    "        \"unique_words\": unique_words,\n",
    "        \"lexical_diversity\": lexical_diversity,\n",
    "        \"grammar_errors\": grammar_errors,\n",
    "    }\n",
    "    pass\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def apply_metric (df):\n",
    "    df['essay_ESL'] = df['essay_ESL'].astype(str)\n",
    "    df['essay_AAE'] = df['essay_AAE'].astype(str)\n",
    "    df['essay_base'] = df['essay_base'].astype(str)\n",
    "\n",
    "    if 'metrics_SAE' not in df.columns:\n",
    "        df['metrics_SAE'] = [{} for _ in range(len(df))]\n",
    "\n",
    "    # Loop through each essay\n",
    "    for index, row in df.iterrows():\n",
    "        # Check if the analysis has not been done for this row\n",
    "        if not row['metrics_SAE']:\n",
    "            try:\n",
    "                # Analyze the essay\n",
    "                essay_metrics = analyze_essay(row['essay_base'])\n",
    "                # Save the analysis result to the 'metrics_ESL' column\n",
    "                df.at[index, 'metrics_SAE'] = essay_metrics\n",
    "            except Exception as e:\n",
    "                # Log or print the error and continue\n",
    "                print(f\"Error processing essay at index {index}: {e}\")\n",
    "\n",
    "\n",
    "    if 'metrics_AAE' not in df.columns:\n",
    "        df['metrics_AAE'] = [{} for _ in range(len(df))]\n",
    "\n",
    "    # Loop through each essay\n",
    "    for index, row in df.iterrows():\n",
    "        # Check if the analysis has not been done for this row\n",
    "        if not row['metrics_AAE']:\n",
    "            try:\n",
    "                # Analyze the essay\n",
    "                essay_metrics = analyze_essay(row['essay_AAE'])\n",
    "                # Save the analysis result to the 'metrics_ESL' column\n",
    "                df.at[index, 'metrics_AAE'] = essay_metrics\n",
    "            except Exception as e:\n",
    "                # Log or print the error and continue\n",
    "                print(f\"Error processing essay at index {index}: {e}\")\n",
    "\n",
    "\n",
    "    if 'metrics_ESL' not in df.columns:\n",
    "        df['metrics_ESL'] = [{} for _ in range(len(df))]\n",
    "\n",
    "    # Loop through each essay\n",
    "    for index, row in df.iterrows():\n",
    "        # Check if the analysis has not been done for this row\n",
    "        if not row['metrics_ESL']:\n",
    "            try:\n",
    "                # Analyze the essay\n",
    "                essay_metrics = analyze_essay(row['essay_ESL'])\n",
    "                # Save the analysis result to the 'metrics_ESL' column\n",
    "                df.at[index, 'metrics_ESL'] = essay_metrics\n",
    "            except Exception as e:\n",
    "                # Log or print the error and continue\n",
    "                print(f\"Error processing essay at index {index}: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd \n",
    "gpt = pd.read_csv('all_essays_gpt.csv', sep=';')\n",
    "gemini = pd.read_csv('all_essays_gemini.csv', sep=';')\n",
    "llama70b = pd.read_csv('all_essays_llama.csv', sep=';')\n",
    "llama7b = pd.read_csv('all_essays_llama7B.csv', sep=';')\n",
    "llama13b = pd.read_csv('all_essays_llama13B.csv', sep=';')\n",
    "vicuna7b = pd.read_csv('all_essays_vicuna7B.csv', sep=';')\n",
    "vicuna13b = pd.read_csv('all_essays_vicuna13B.csv', sep=';')\n",
    "alpaca = pd.read_csv('all_essays_alpaca.csv', sep=';')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing essay at index 247: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/check?language=en-US&text=The+use+of+academic+honor+codes+in+colleges+and+universities+has+been+shown+to+be+a+highly+effective+method+of+deterring+cheating+among+students.+Unlike+other+methods%2C+such+as+closely+monitoring+students+by+teachers%2C+honor+codes+rely+on+students+agreeing+not+to+cheat+and+to+report+any+instances+of+cheating+they+witness.+The+success+of+honor+codes+can+be+seen+in+the+case+of+Groveton+College%2C+which+adopted+an+honor+code+and+discontinued+its+old+system+of+teacher+monitoring.+In+the+first+year+of+the+honor+code%2C+students+reported+twenty-one+cases+of+cheating%2C+compared+to+an+average+of+dirty+cases+per+year+under+the+old+system.+Five+years+later%2C+the+number+of+reported+cases+of+cheating+had+dropped+to+fourteen.%0A%0AIn+addition+to+the+reduction+in+cheating%2C+a+recent+survey+of+Groveton+students+found+that+a+majority+would+be+less+likely+to+cheat+with+an+honor+code+in+place+than+without.+This+suggests+that+the+presence+of+an+honor+code+not+only+deters+cheating%2C+but+also+increases+student+trust+in+the+academic+system+and+promotes+a+sense+of+responsibility+and+integrity+among+students.%0A%0AThe+effectiveness+of+honor+codes+can+be+attributed+to+several+factors.+First%2C+honor+codes+create+a+sense+of+community+among+students%2C+as+they+are+all+working+together+to+uphold+the+code+and+maintain+the+integrity+of+the+academic+system.+Second%2C+honor+codes+provide+students+with+a+sense+of+ownership+and+responsibility+for+their+academic+success%2C+as+they+are+the+ones+who+are+responsible+for+upholding+the+code+and+reporting+instances+of+cheating.+Finally%2C+honor+codes+can+be+seen+as+a+more+student-centered+approach+to+academic+integrity%2C+as+they+rely+on+students+to+police+themselves+and+report+instances+of+cheating%2C+rather+than+relying+on+teachers+to+monitor+and+police+students.%0A%0AIn+conclusion%2C+the+evidence+suggests+that+academic+honor+codes+are+far+more+successful+than+other+methods+at+deterring+cheating+among+students+at+colleges+and+universities.+The+success+of+honor+codes+can+be+seen+in+the+reduction+in+cheating+cases+and+the+increase+in+student+trust+and+responsibility.+As+such%2C+it+is+clear+that+honor+codes+play+an+important+role+in+maintaining+the+integrity+of+the+academic+system+and+should+continue+to+be+used+in+colleges+and+universities. (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbc10>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 248: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db970>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 249: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db040>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 250: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788803d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 251: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880be0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 252: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788813f0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 253: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db310>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 254: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db0d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 255: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880fa0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 256: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880f40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 257: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880580>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 258: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881c00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 259: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dad10>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 260: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db310>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 261: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788805b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 262: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788812a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 263: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788815a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 264: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dafe0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 265: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbc70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 266: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881d20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 267: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880fa0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 268: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880640>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 269: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882410>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 270: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db430>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 271: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dafe0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 272: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880c10>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 273: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788814b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 274: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881de0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 275: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 276: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbca0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 277: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882560>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 278: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881600>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 279: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788811e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 280: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882c20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 281: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db0d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 282: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786daef0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 283: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788813c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 284: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880d00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 285: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788825f0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 286: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbf40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 287: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d8ca0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 288: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881cf0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 289: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788813f0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 290: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881090>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 291: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882ce0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 292: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbd00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 293: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db490>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 294: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788810f0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 295: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881120>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 296: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882f50>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 297: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db370>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 298: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 299: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbb80>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 300: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788828c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 301: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881fc0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 302: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788824a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 303: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786da020>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 304: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d9b40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 305: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881870>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 306: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882620>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 307: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788805b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 308: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786daf50>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 309: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db340>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 310: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db9d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 311: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882500>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 312: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882590>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 313: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881bd0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 314: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db760>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 315: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d94e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 316: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880790>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 317: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882710>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 318: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882170>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 319: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbd60>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 320: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dad40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 321: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882a10>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 322: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880c70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 323: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882d70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 324: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883430>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 325: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 326: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d94e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 327: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881150>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 328: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882200>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 329: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882800>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 330: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbbb0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 331: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db850>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 332: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883550>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 333: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881cf0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 334: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880e20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 335: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883c40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 336: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbeb0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 337: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dba60>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 338: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788817b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 339: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788821a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 340: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883610>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 341: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883160>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 342: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880100>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 343: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880b20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 344: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbdf0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 345: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db2b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 346: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178868490>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 347: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d94e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 348: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880af0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 349: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788826b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 350: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883220>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 351: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x17863ff40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 352: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db250>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 353: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d9e70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 354: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880160>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 355: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883220>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 356: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881ea0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 357: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881330>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 358: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db2e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 359: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786da5c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 360: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880430>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 361: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883580>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 362: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883af0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 363: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db9a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 364: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbbb0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 365: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbf10>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 366: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 367: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882a70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 368: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883280>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 369: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db640>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 370: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db0d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 371: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882e30>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 372: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788836a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 373: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881f30>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 374: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db370>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 375: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 376: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786da020>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 377: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880e80>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 378: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882170>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 379: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881ba0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 380: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db5e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 381: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dada0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 382: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883010>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 383: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880490>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 384: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880d90>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 385: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db400>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 386: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbd90>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 387: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882d40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 388: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788815d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 389: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788800a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 390: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882b00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 391: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db970>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 392: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d8940>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 393: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880940>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 394: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788837c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 395: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881180>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 396: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dad40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 397: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbfa0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 398: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788820b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 399: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883430>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 400: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881ed0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 401: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880c40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 402: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbd90>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 403: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d9b40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 404: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882590>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 405: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881e70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 406: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880700>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 407: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881450>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 408: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881510>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 409: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881ed0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 410: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d8940>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 411: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db070>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 412: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178888490>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 413: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 414: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881ff0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 415: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882dd0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 416: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882b30>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 417: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788885e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 418: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d8940>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 419: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbd00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 420: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881030>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 421: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880fa0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 422: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883970>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 423: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786daa40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 424: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db2e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 425: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881510>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 426: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882d70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 427: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788815a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 428: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883d30>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 429: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db850>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 430: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db2b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 431: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881f00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 432: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883df0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 433: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882bc0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 434: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dba90>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 435: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbb20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 436: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881ae0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 437: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788812a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 438: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880d90>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 439: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882a70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 440: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786da6e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 441: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786da5c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 442: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880fd0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 443: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881510>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 444: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883f70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 445: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbca0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 446: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db1c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 447: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883400>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 448: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882050>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 449: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881480>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 450: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883910>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 451: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db670>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 452: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db880>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 453: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881600>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 454: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882bc0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 455: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883eb0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 456: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbfa0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 457: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbf40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 458: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883dc0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 459: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788812a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 460: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883b20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 461: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788821d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 462: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db9a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 463: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178543850>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 464: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788825c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 465: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788822c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 466: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881420>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 467: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880ca0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 468: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883460>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 469: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881270>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 470: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db2e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 471: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db3d0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 472: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x17882c5e0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 473: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786daa40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 474: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881090>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 475: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788808b0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 476: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882c20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 477: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x17882c040>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 478: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881420>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 479: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882440>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 480: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788822f0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 481: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db1c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 482: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db670>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 483: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x17882cdf0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 484: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db250>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 485: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dba60>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 486: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880160>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 487: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882ef0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 488: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788833a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 489: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db640>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 490: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786db970>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 491: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880370>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 492: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883b80>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 493: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882140>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 494: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788821a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 495: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dafe0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 496: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dba00>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 497: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880fa0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 498: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881b10>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 499: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881cc0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 500: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d9b40>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 501: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dad70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 502: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788801c0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 503: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883f70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 504: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880730>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 505: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178880670>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 506: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbca0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 507: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d9390>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 508: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882530>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 509: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1788833a0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 510: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882bc0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 511: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbc70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 512: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786dbb80>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 513: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883fd0>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 514: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178883b80>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 515: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178882c20>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 516: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x178881210>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n",
      "Error processing essay at index 517: https://languagetool.org/api/v2/: HTTPSConnectionPool(host='languagetool.org', port=443): Max retries exceeded with url: /api/v2/languages (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x1786d9e70>: Failed to resolve 'languagetool.org' ([Errno 8] nodename nor servname provided, or not known)\"))\n"
     ]
    }
   ],
   "source": [
    "#apply_metric(gpt) \n",
    "#apply_metric(gemini)\n",
    "#apply_metric(llama70b) \n",
    "#apply_metric(llama7b) \n",
    "#apply_metric(llama13b)\n",
    "apply_metric(vicuna7b)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing essay at index 21: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 52: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 71: <!DOCTYPE html>\n",
      "<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n",
      "<head>\n",
      "\n",
      "\n",
      "<title>languagetool.org | 502: Bad gateway</title>\n",
      "<meta charset=\"UTF-8\" />\n",
      "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n",
      "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n",
      "<meta name=\"robots\" content=\"noindex, nofollow\" />\n",
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n",
      "<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n",
      "\n",
      "\n",
      "</head>\n",
      "<body>\n",
      "<div id=\"cf-wrapper\">\n",
      "    <div id=\"cf-error-details\" class=\"p-0\">\n",
      "        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n",
      "            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n",
      "              <span class=\"inline-block\">Bad gateway</span>\n",
      "              <span class=\"code-label\">Error code 502</span>\n",
      "            </h1>\n",
      "            <div>\n",
      "               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n",
      "            </div>\n",
      "            <div class=\"mt-3\">2024-03-11 22:20:37 UTC</div>\n",
      "        </header>\n",
      "        <div class=\"my-8 bg-gradient-gray\">\n",
      "            <div class=\"w-240 lg:w-full mx-auto\">\n",
      "                <div class=\"clearfix md:px-8\">\n",
      "                  \n",
      "<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">You</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Browser\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    </a>\n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">Frankfurt</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    Cloudflare\n",
      "    </a>\n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">languagetool.org</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Host\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n",
      "</div>\n",
      "\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n",
      "            <div class=\"clearfix\">\n",
      "                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n",
      "                    <p>The web server reported a bad gateway error.</p>\n",
      "                </div>\n",
      "                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n",
      "                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n",
      "  <p class=\"text-13\">\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">862eee549da02c71</strong></span>\n",
      "    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n",
      "      Your IP:\n",
      "      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n",
      "      <span class=\"hidden\" id=\"cf-footer-ip\">2003:ec:8f49:83b8:f909:88ab:4405:bdb6</span>\n",
      "      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    </span>\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n",
      "    \n",
      "  </p>\n",
      "  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n",
      "</div><!-- /.error-footer -->\n",
      "\n",
      "\n",
      "    </div>\n",
      "</div>\n",
      "</body>\n",
      "</html>\n",
      "\n",
      "Error processing essay at index 77: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 88: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 146: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 180: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 209: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 284: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 303: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 426: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 461: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 463: <!DOCTYPE html>\n",
      "<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n",
      "<head>\n",
      "\n",
      "\n",
      "<title>languagetool.org | 502: Bad gateway</title>\n",
      "<meta charset=\"UTF-8\" />\n",
      "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n",
      "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n",
      "<meta name=\"robots\" content=\"noindex, nofollow\" />\n",
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n",
      "<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n",
      "\n",
      "\n",
      "</head>\n",
      "<body>\n",
      "<div id=\"cf-wrapper\">\n",
      "    <div id=\"cf-error-details\" class=\"p-0\">\n",
      "        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n",
      "            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n",
      "              <span class=\"inline-block\">Bad gateway</span>\n",
      "              <span class=\"code-label\">Error code 502</span>\n",
      "            </h1>\n",
      "            <div>\n",
      "               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n",
      "            </div>\n",
      "            <div class=\"mt-3\">2024-03-11 22:40:17 UTC</div>\n",
      "        </header>\n",
      "        <div class=\"my-8 bg-gradient-gray\">\n",
      "            <div class=\"w-240 lg:w-full mx-auto\">\n",
      "                <div class=\"clearfix md:px-8\">\n",
      "                  \n",
      "<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">You</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Browser\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    </a>\n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">Frankfurt</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    Cloudflare\n",
      "    </a>\n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">languagetool.org</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Host\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n",
      "</div>\n",
      "\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n",
      "            <div class=\"clearfix\">\n",
      "                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n",
      "                    <p>The web server reported a bad gateway error.</p>\n",
      "                </div>\n",
      "                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n",
      "                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n",
      "  <p class=\"text-13\">\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">862f0b709e446910</strong></span>\n",
      "    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n",
      "      Your IP:\n",
      "      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n",
      "      <span class=\"hidden\" id=\"cf-footer-ip\">2003:ec:8f49:83b8:f909:88ab:4405:bdb6</span>\n",
      "      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    </span>\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n",
      "    \n",
      "  </p>\n",
      "  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n",
      "</div><!-- /.error-footer -->\n",
      "\n",
      "\n",
      "    </div>\n",
      "</div>\n",
      "</body>\n",
      "</html>\n",
      "\n",
      "Error processing essay at index 468: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 481: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 499: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 45: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 46: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 52: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 54: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 67: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 112: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 165: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 197: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 217: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 261: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 331: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 370: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 466: <!DOCTYPE html>\n",
      "<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n",
      "<head>\n",
      "\n",
      "\n",
      "<title>languagetool.org | 502: Bad gateway</title>\n",
      "<meta charset=\"UTF-8\" />\n",
      "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n",
      "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n",
      "<meta name=\"robots\" content=\"noindex, nofollow\" />\n",
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n",
      "<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n",
      "\n",
      "\n",
      "</head>\n",
      "<body>\n",
      "<div id=\"cf-wrapper\">\n",
      "    <div id=\"cf-error-details\" class=\"p-0\">\n",
      "        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n",
      "            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n",
      "              <span class=\"inline-block\">Bad gateway</span>\n",
      "              <span class=\"code-label\">Error code 502</span>\n",
      "            </h1>\n",
      "            <div>\n",
      "               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n",
      "            </div>\n",
      "            <div class=\"mt-3\">2024-03-11 23:10:47 UTC</div>\n",
      "        </header>\n",
      "        <div class=\"my-8 bg-gradient-gray\">\n",
      "            <div class=\"w-240 lg:w-full mx-auto\">\n",
      "                <div class=\"clearfix md:px-8\">\n",
      "                  \n",
      "<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">You</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Browser\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    </a>\n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">Frankfurt</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    Cloudflare\n",
      "    </a>\n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">languagetool.org</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Host\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n",
      "</div>\n",
      "\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n",
      "            <div class=\"clearfix\">\n",
      "                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n",
      "                    <p>The web server reported a bad gateway error.</p>\n",
      "                </div>\n",
      "                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n",
      "                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n",
      "  <p class=\"text-13\">\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">862f38365b1c8f36</strong></span>\n",
      "    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n",
      "      Your IP:\n",
      "      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n",
      "      <span class=\"hidden\" id=\"cf-footer-ip\">2003:ec:8f49:83b8:f909:88ab:4405:bdb6</span>\n",
      "      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    </span>\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n",
      "    \n",
      "  </p>\n",
      "  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n",
      "</div><!-- /.error-footer -->\n",
      "\n",
      "\n",
      "    </div>\n",
      "</div>\n",
      "</body>\n",
      "</html>\n",
      "\n",
      "Error processing essay at index 489: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 502: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 7: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 130: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 143: <!DOCTYPE html>\n",
      "<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n",
      "<head>\n",
      "\n",
      "\n",
      "<title>languagetool.org | 502: Bad gateway</title>\n",
      "<meta charset=\"UTF-8\" />\n",
      "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n",
      "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n",
      "<meta name=\"robots\" content=\"noindex, nofollow\" />\n",
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n",
      "<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n",
      "\n",
      "\n",
      "</head>\n",
      "<body>\n",
      "<div id=\"cf-wrapper\">\n",
      "    <div id=\"cf-error-details\" class=\"p-0\">\n",
      "        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n",
      "            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n",
      "              <span class=\"inline-block\">Bad gateway</span>\n",
      "              <span class=\"code-label\">Error code 502</span>\n",
      "            </h1>\n",
      "            <div>\n",
      "               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n",
      "            </div>\n",
      "            <div class=\"mt-3\">2024-03-11 23:19:42 UTC</div>\n",
      "        </header>\n",
      "        <div class=\"my-8 bg-gradient-gray\">\n",
      "            <div class=\"w-240 lg:w-full mx-auto\">\n",
      "                <div class=\"clearfix md:px-8\">\n",
      "                  \n",
      "<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">You</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Browser\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    </a>\n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">Frankfurt</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    Cloudflare\n",
      "    </a>\n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">languagetool.org</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Host\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n",
      "</div>\n",
      "\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n",
      "            <div class=\"clearfix\">\n",
      "                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n",
      "                    <p>The web server reported a bad gateway error.</p>\n",
      "                </div>\n",
      "                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n",
      "                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n",
      "  <p class=\"text-13\">\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">862f44c35aa19265</strong></span>\n",
      "    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n",
      "      Your IP:\n",
      "      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n",
      "      <span class=\"hidden\" id=\"cf-footer-ip\">2003:ec:8f49:83b8:f909:88ab:4405:bdb6</span>\n",
      "      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    </span>\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n",
      "    \n",
      "  </p>\n",
      "  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n",
      "</div><!-- /.error-footer -->\n",
      "\n",
      "\n",
      "    </div>\n",
      "</div>\n",
      "</body>\n",
      "</html>\n",
      "\n",
      "Error processing essay at index 234: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 246: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 479: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 493: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 509: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n"
     ]
    }
   ],
   "source": [
    "apply_metric(vicuna13b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing essay at index 0: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 117: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 125: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 136: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 261: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 275: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 351: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 391: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 137: <!DOCTYPE html>\n",
      "<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n",
      "<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n",
      "<head>\n",
      "\n",
      "\n",
      "<title>languagetool.org | 502: Bad gateway</title>\n",
      "<meta charset=\"UTF-8\" />\n",
      "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n",
      "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n",
      "<meta name=\"robots\" content=\"noindex, nofollow\" />\n",
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n",
      "<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n",
      "\n",
      "\n",
      "</head>\n",
      "<body>\n",
      "<div id=\"cf-wrapper\">\n",
      "    <div id=\"cf-error-details\" class=\"p-0\">\n",
      "        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n",
      "            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n",
      "              <span class=\"inline-block\">Bad gateway</span>\n",
      "              <span class=\"code-label\">Error code 502</span>\n",
      "            </h1>\n",
      "            <div>\n",
      "               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n",
      "            </div>\n",
      "            <div class=\"mt-3\">2024-03-12 00:01:18 UTC</div>\n",
      "        </header>\n",
      "        <div class=\"my-8 bg-gradient-gray\">\n",
      "            <div class=\"w-240 lg:w-full mx-auto\">\n",
      "                <div class=\"clearfix md:px-8\">\n",
      "                  \n",
      "<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">You</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Browser\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    </a>\n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">Frankfurt</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" target=\"_blank\" rel=\"noopener noreferrer\">\n",
      "    Cloudflare\n",
      "    </a>\n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n",
      "</div>\n",
      "\n",
      "<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n",
      "  <div class=\"relative mb-10 md:m-0\">\n",
      "    \n",
      "    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n",
      "    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n",
      "    \n",
      "  </div>\n",
      "  <span class=\"md:block w-full truncate\">languagetool.org</span>\n",
      "  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n",
      "    \n",
      "    Host\n",
      "    \n",
      "  </h3>\n",
      "  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n",
      "</div>\n",
      "\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n",
      "            <div class=\"clearfix\">\n",
      "                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n",
      "                    <p>The web server reported a bad gateway error.</p>\n",
      "                </div>\n",
      "                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n",
      "                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n",
      "                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n",
      "                </div>\n",
      "            </div>\n",
      "        </div>\n",
      "\n",
      "        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n",
      "  <p class=\"text-13\">\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">862f824888725d41</strong></span>\n",
      "    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n",
      "      Your IP:\n",
      "      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n",
      "      <span class=\"hidden\" id=\"cf-footer-ip\">2003:ec:8f49:83b8:f909:88ab:4405:bdb6</span>\n",
      "      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n",
      "    </span>\n",
      "    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=languagetool.org\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n",
      "    \n",
      "  </p>\n",
      "  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n",
      "</div><!-- /.error-footer -->\n",
      "\n",
      "\n",
      "    </div>\n",
      "</div>\n",
      "</body>\n",
      "</html>\n",
      "\n",
      "Error processing essay at index 276: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 284: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 377: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 471: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n",
      "Error processing essay at index 62: Error: Checking took longer than 20.0 seconds, which is this server's limit. Please make sure you have selected the proper language or consider submitting a shorter text.\n"
     ]
    }
   ],
   "source": [
    "apply_metric(alpaca)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "gpt.to_csv('all_essays_gpt.csv', sep=';')\n",
    "gemini.to_csv('all_essays_gemini.csv', sep=';')\n",
    "llama70b.to_csv('all_essays_llama.csv', sep=';')\n",
    "llama7b.to_csv('all_essays_llama7B.csv', sep=';')\n",
    "llama13b.to_csv('all_essays_llama13B.csv', sep=';')\n",
    "vicuna7b.to_csv('all_essays_vicuna7B.csv', sep=';')\n",
    "vicuna13b.to_csv('all_essays_vicuna13B.csv', sep=';')\n",
    "alpaca.to_csv('all_essays_alpaca.csv', sep=';')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "import pandas as pd \n",
    "\n",
    "def convert_results(df, model_name):\n",
    "# Convert dictionaries to DataFrame\n",
    "    df_SAE = pd.DataFrame(list(df['metrics_SAE']))\n",
    "    df_ESL = pd.DataFrame(list(df['metrics_ESL']))\n",
    "    df_AAE = pd.DataFrame(list(df['metrics_AAE']))\n",
    "\n",
    "    # Calculate means\n",
    "    means_SAE = df_SAE.mean()\n",
    "    means_ESL = df_ESL.mean()\n",
    "    means_AAE = df_AAE.mean()\n",
    "\n",
    "\n",
    "    results = pd.concat([means_SAE, means_ESL, means_AAE], axis=1, keys=['SAE', 'ESL', 'AAE'])\n",
    "    results.to_csv(f'results_{model_name}.csv')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "test",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
